server:
  port: 9004
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
    register-with-eureka: true
    fetch-registry: false
logging:
  level:
    root: debug